# Generated by Django 4.2.7 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Lamout Perfume', max_length=100)),
                ('tagline', models.CharField(default='Discover exquisite fragrances that define your unique style', max_length=200)),
                ('phone_number', models.CharField(default='+254616301107', max_length=20)),
                ('email', models.EmailField(default='info@lamoutperfume.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+254616301107', max_length=20)),
                ('address_line_1', models.CharField(default='Neema House, First Floor', max_length=100)),
                ('address_line_2', models.CharField(default='Room 1007', max_length=100)),
                ('city', models.CharField(default='Githunguri', max_length=50)),
                ('county', models.CharField(default='Kiambu', max_length=50)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('opening_hours', models.TextField(default='Monday - Saturday: 9:00 AM - 6:00 PM\nSunday: 10:00 AM - 4:00 PM')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('hero_title', models.CharField(default='Welcome to Lamout Perfume', max_length=100)),
                ('hero_subtitle', models.CharField(default='Discover exquisite fragrances that define your unique style', max_length=200)),
                ('about_us', models.TextField(default='We specialize in premium perfumes for men and women, offering both packaged bottles and custom ML measurements to suit your preferences.')),
                ('current_discount_percentage', models.PositiveIntegerField(default=0, help_text='Current site-wide discount %')),
                ('discount_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount for discount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
    ]
