# Generated by Django 4.2.7 on 2025-09-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mens', "Men's Collection"), ('ladies', "Ladies' Collection"), ('unisex', 'Unisex'), ('woody', 'Woody'), ('fresh', 'Fresh'), ('oriental', 'Oriental'), ('floral', 'Floral')], default='unisex', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for one full package', max_digits=10)),
                ('ml_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per ml (for custom quantities)', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=100, help_text='Number of available full packages')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx'), models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_custom_ml', models.BooleanField(default=False)),
                ('custom_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'unique_together': {('cart', 'product', 'is_custom_ml', 'custom_ml')},
            },
        ),
    ]
