# Generated by Django 4.2.7 on 2025-09-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', "Men's Collection"), ('ladies', "Ladies' Collection"), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
    ]
